name: clang-format Code Formatter

on: [push, pull_request]  # Trigger on both push and pull request events

jobs:
  lint:
    name: Clang Code Formatter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Ensure that your repository is checked out

    - name: Run clang-format
      uses: git-auto-commit-action/clang-format-action@v1  # Use this clang-format action
      with:
        clang-version: 14  # Specify the clang version
        extensions: 'cpp,h,hpp'  # Specify the file extensions to format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token
