name: clang-format Code Formatter

on: [push, pull_request]  # Trigger on both push and pull requests

jobs:
  lint:
    name: Clang Code Formatter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Ensure that your repository is checked out

    - name: Run clang-format
      uses: Doctest/clang-format@v1  # Use a different action for clang-format
      with:
        extensions: 'cpp,h,hpp'  # Specify which file extensions to check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token
